### ISSUE TITLE
Localhost on windows not working

### ISSUE THREAD

**Issue by mimcomp** [375670450/StockInformationSystem#9]
When try StockInformationSystem on localhost windows more issues..What is options and guide to working on windows as localhost?

**Comment by stardust95** [comment]
Just follow the commands in README.md. What kinds of problems you have when it runs on your computer? Could you post some screenshots about them?

**Comment by mimcomp** [comment]
Hi,
Sorry i am new  with python..
I tried it with more options and update but same problems..
How i can change it to Mysql ?
![stch](https://user-images.githubusercontent.com/30536517/30936117-81fea7d8-a3db-11e7-8c5c-60fe09dd6786.png)

**Comment by stardust95** [comment]
It seems like your node version is too old to support ES6. You can try reinstall the latest stable version of node.js and run the commands again.

**Comment by mimcomp** [comment]
Hi,
I updated nodejs and i installed Redis , errors is :- 

    at Protocol.handshake (C:\pyscript\venu\app\Stockchina\Server\node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at PoolConnection.connect (C:\pyscript\venu\app\Stockchina\Server\node_modules\mysql\lib\Connection.js:130:18)
    at Pool.getConnection (C:\pyscript\venu\app\Stockchina\Server\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\pyscript\venu\app\Stockchina\Server\node_modules\mysql\lib\Pool.js:202:8)
    at Function.getCodesList (C:\pyscript\venu\app\Stockchina\Server\models\IndexData.js:18:14)
    at Object.<anonymous> (C:\pyscript\venu\app\Stockchina\Server\routes\index.js:21:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'tdsql-219vguff.sh.cdb.myqcloud.com',
  host: 'tdsql-219vguff.sh.cdb.myqcloud.com',
  port: '26',
  fatal: true }
Redis Error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Redis Error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Redis Error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
trade
Redis Error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
connection err
Redis Error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Redis Error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379

Can you send me you email and my email is mimcompatgmail.
Thanks

**Comment by stardust95** [comment]
Firstly, you need to replace the mysql connection parameters(host, user, passwd) in DbConnection.js.

Secondly, ensure your redis is launched and listening at your locahost:6379.

BTW my email is pb375670450@gmail.com.
